const fs = require('fs');
const path = require('path');
const Babel = require('@babel/standalone');
const terser = require('terser');

const root = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const write = (file, content) => fs.writeFileSync(path.join(root, file), content);
const ensureDir = (dir) => fs.mkdirSync(path.join(root, dir), { recursive: true });

function between(source, start, end, label) {
  const a = source.indexOf(start);
  const b = source.indexOf(end, a + start.length);
  if (a === -1 || b === -1) throw new Error(`Could not extract ${label}`);
  return source.slice(a + start.length, b);
}

function syncServiceWorkerChunks(chunks) {
  const swPath = path.join(root, 'service-worker.js');
  if (!fs.existsSync(swPath)) return;
  const chunkBlock = chunks.map((file) => `  './${file}',`).join('\n');
  const sw = fs.readFileSync(swPath, 'utf8');
  const next = sw.replace(/  '\.\/app-chunks\/app\.\d+\.js',\r?\n(?:  '\.\/app-chunks\/app\.\d+\.js',\r?\n)*/g, `${chunkBlock}\n`);
  if (next !== sw) fs.writeFileSync(swPath, next);
}

async function main() {
  const html = read('index.html');
  const css = between(html, '<style>', '</style>', 'CSS').trim();
  const appJsx = between(html, '<script type="text/babel">', '</script>', 'JSX app').trim();
  const swRegistration = between(
    html,
    '<!-- ============ Register the service worker (enables offline + install) ============ -->',
    '</body>',
    'service worker registration'
  ).trim();

  const compiled = Babel.transform(appJsx, {
    presets: [['react', { runtime: 'classic' }]],
    comments: false,
    compact: false
  }).code;

  const minified = await terser.minify(compiled, {
    compress: {
      passes: 2
    },
    mangle: true,
    format: {
      comments: false
    }
  });

  if (minified.error) throw minified.error;

  const bundle = [
    '/* IronLog compiled app bundle. Generated by tools/build-v2.js. */',
    minified.code,
    ''
  ].join('\n');

  const chunkDir = 'app-chunks';
  ensureDir(chunkDir);
  for (const file of fs.readdirSync(path.join(root, chunkDir))) {
    if (/^app\.\d+\.js$/.test(file)) fs.unlinkSync(path.join(root, chunkDir, file));
  }

  const chunkSize = 12000;
  const chunks = [];
  for (let i = 0; i < bundle.length; i += chunkSize) {
    const name = `${chunkDir}/app.${String(chunks.length).padStart(2, '0')}.js`;
    write(name, bundle.slice(i, i + chunkSize));
    chunks.push(name);
  }

  const loader = `(function(){\n  const chunks = ${JSON.stringify(chunks)};\n  const root = new URL('.', document.currentScript.src);\n  const error = (message) => {\n    const el = document.getElementById('root') || document.body;\n    el.innerHTML = '<div style="padding:24px;font-family:system-ui,sans-serif;color:#eef0f7;background:#0d0e16;min-height:100vh"><h1 style="font-size:20px">IronLog could not start</h1><p style="color:#a3aab8">' + message + '</p></div>';\n  };\n  Promise.all(chunks.map((file) => fetch(new URL(file, root), { cache: 'no-cache' }).then((res) => {\n    if (!res.ok) throw new Error(file + ' failed with ' + res.status);\n    return res.text();\n  }))).then((parts) => {\n    (0, eval)(parts.join(''));\n  }).catch((err) => {\n    console.error('IronLog bundle load failed', err);\n    error('Refresh once. If it still fails, clear the app cache and open IronLog again.');\n  });\n})();\n`;

  const shell = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover" />
<title>IronLog - Workout Tracker</title>
<link rel="manifest" href="manifest.json" />
<meta name="theme-color" content="#0d0e16" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
<meta name="apple-mobile-web-app-title" content="IronLog" />
<link rel="apple-touch-icon" href="apple-touch-icon.png" />
<link rel="icon" type="image/png" sizes="192x192" href="icon-192.png" />
<link rel="icon" type="image/png" sizes="32x32" href="favicon-32.png" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Archivo:wght@500;600;700;800&family=Manrope:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
${css}
</style>
</head>
<body>
<div id="root"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/18.3.1/umd/react.production.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.3.1/umd/react-dom.production.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.min.js"></script>
<script src="app-loader.js"></script>
${swRegistration}
</body>
</html>
`;

  write('app.bundle.js', bundle);
  write('app-loader.js', loader);
  write('index-v2.html', shell);
  syncServiceWorkerChunks(chunks);

  console.log(JSON.stringify({
    cssBytes: Buffer.byteLength(css),
    jsxBytes: Buffer.byteLength(appJsx),
    bundleBytes: Buffer.byteLength(bundle),
    shellBytes: Buffer.byteLength(shell),
    chunkCount: chunks.length
  }, null, 2));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
